core/urls.py
from django.urls import path, re_path
from . import views


app_name = 'core'

urlpatterns = [
# page for practice circle canvas and netflix scroller
path('menu/',views.HtmlPractice.as_view(), name='practice'),
path('userprofile/create/',views.User_Profile_Create.as_view(), name = 'user_create'),
path('userprofile/update/<slug>/',views.User_Profile_Update.as_view(), name = 'user_update'),

path('group/<slug>/',views.Detail_Group.as_view(), name ='group'),

path('',views.User_Dashboard.as_view(),name ='user_dashboard'),

# zoom
path('zoom/',views.TestZoom.as_view(), name ='zoom'),
path('zoom-display/',views.DisplayZoom.as_view(), name ='zoomdisplay'),

#urls related to posting /////////////////
path('profile/post/<int:pk>/',views.Detail_Post.as_view(), name ='post-detail'),

#group_send
#oage to create group
path('group-create/',views.Create_DividendWealthGroup.as_view(), name ='create-group'),

#group landing page
path('group/<slug>/landing-page/',views.Group_Landing_Page.as_view(), name ='group-landing'),

path('feed/',views.Feed.as_view(), name ='feed'),
#<int:pk>
path('ajax/',views.TestAjax.as_view(), name='ajax'),
# page for user to choose membership
path('memberships/',views.Membership_Choice.as_view(), name ='membership_choice'),
#page for user account
path('account/<username>/',views.DividendWealthAccount.as_view(), name ='user_account'),

#useful test zone below
]

core/forms.py
from django import forms
from .models import Stocks, User_Profile, StockInfo,Post,GenGroup,Comments
from tinymce import TinyMCE
from django.forms import Textarea
from dal import autocomplete
class StocksModelForm(forms.ModelForm):
    class Meta:
        model = Stocks
        fields = ['ticker','company_name','price','profile_pic','fairvale','dividend_yeild','dividend_growth','earning_growth','distrubution','months','url']

class User_profile_form(forms.ModelForm):
    class Meta:
        model = User_Profile
        exclude = ["user","sign_up_date","slug"]

class Stock_profile_form(forms.ModelForm):
    class Meta:
        model = StockInfo
        exclude = ["userprofile","stock","date_included"]

class GenGroupForm(forms.ModelForm):
    class Meta:
        model = GenGroup
        exclude =["creator","slug"]

class PostComment(forms.ModelForm):

    class Meta:
        model = Comments
        fields =('contents',)
        exclude =["author","post","stock","likes"]
        widgets = {
            'contents': Textarea(attrs={'class':'col-8 offset-2','cols': 40, 'rows': 10}),

        }
        labels ={
            'contents': '',
        }

#for creating a post/////////////////////////////
class TinyMCEWidget(TinyMCE):
    def use_required_attribute(self, *args):
        return False


class PostForm(forms.ModelForm):
    content = forms.CharField(
        widget=TinyMCEWidget(
            attrs={'required': False, 'cols': 10, 'rows': 10}
        )
    )

    class Meta:
        model = Post
        exclude =["author","likes","viewcount","comment_count","topic","comment_count","repost","repost_count"]
        widgets = {
            'description': Textarea(attrs={'height': '59px', 'rows': 2,}),

            'stocks': autocomplete.ModelSelect2Multiple(
                url='core:stock-autocomplete',
                attrs={
                        # Set some placeholder

                        # Only trigger autocompletion after 3 characters have been typed
                        'data-minimum-input-length': 1,

                        'class': 'list-inline-item',
                        'width': '0px',
                        'type':'hidden'
    },


            ),

        }

core/views.py
import os

from django.conf import settings
from django.http import JsonResponse
from django.contrib import messages
from django.shortcuts import render, get_object_or_404, redirect
from .models import (Item, OrderItem, Order,
User_Profile,Dividend,Article,
Post,Topic,Comments,GenGroup,GroupMember,CommentReply,
Archive,PostArchive,CommentsArchive,CommentReplyArchive,
PostViewCount,PostReport,PostLike,CommentsReport,
CommentsLike,CommentReplyLike,CommentReplyReport,
PostPicture, CommentsPicture, CommentReplyPicture,
WatchlistDownload, File, GroupFileList, FileDownload,
PostUrl, WebsiteUrl,Notification, DividendWealthMembership,
DividendWealthSubscription, UserProfileCards, Cards,
DividendWealthConnectedAccount, DividendWealthConnectedAccountPayments,
GroupCategories,Categories,GroupPayment,GroupSubscription,Credential,UserCredential,
UserFinancialRole,FinancialRole,UserRelationship
)
from django.views import generic
from django.urls import reverse,reverse_lazy
from django.conf import settings #for django allauth
from .forms import StocksModelForm,User_profile_form, Stock_profile_form,PostForm,GenGroupForm,PostComment
from allauth.utils import get_user_model
from django.contrib.auth.models import User
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.core.paginator import Paginator
from django.core.paginator import EmptyPage
from django.core.paginator import PageNotAnInteger

from django.db.models import Q,Sum, F,FloatField
from chartit import PivotDataPool, PivotChart, DataPool, Chart
import requests
from django.utils.dateparse import parse_date
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.edit import ModelFormMixin
from django.views.generic.list import ListView
from dal import autocomplete
from django.utils.safestring import mark_safe
import json
from django.core.files.storage import default_storage
from channels.layers import get_channel_layer
from asgiref.sync import async_to_sync
from datetime import date
from datetime import time
from datetime import datetime,timedelta
import pytz
import re
from django.utils import timezone
from django.http import JsonResponse
from django.utils.text import slugify
import stripe
from django.shortcuts import redirect
import string
from django.utils.timesince import timesince
from django.core.mail import send_mail
from django.template.loader import render_to_string
from django.utils.html import strip_tags
from django.db import connection
import random
import string
from django.contrib.staticfiles.templatetags.staticfiles import static
import http.client
import hashlib
import hmac
import base64
import time

stripe.api_key = settings.STRIPE_SECRET_KEY

from PIL import Image, ExifTags

def rotate_image(filepath):
  try:
    image = Image.open(filepath)
    for orientation in ExifTags.TAGS.keys():
      if ExifTags.TAGS[orientation] == 'Orientation':
            break
    exif = dict(image._getexif().items())

    if exif[orientation] == 3:
        image = image.rotate(180, expand=True)
    elif exif[orientation] == 6:
        image = image.rotate(270, expand=True)
    elif exif[orientation] == 8:
        image = image.rotate(90, expand=True)
    image.save(filepath)
    image.close()
  except (AttributeError, KeyError, IndexError):
    # cases: image don't have getexif
    pass


# https://docs.djangoproject.com/en/3.0/topics/auth/default/

class TestZoom(generic.TemplateView):
    template_name="zoom_test.html"
    def get(self, *args, **kwargs):
        # Section Recive Zoom Credentials
        # only accept zoom credentials when user is authenticated
        if self.request.user.is_authenticated:
            # get the zooom ouath code
            zoom_OAUTH = self.request.GET.getlist('code') if 'code' in self.request.GET else None

            if zoom_OAUTH != None:
                # if we have received the code from zoom get the user
                # get redirect url for zoom oauth flow
                # send a post reqest to zoom to acess user's zoom account
                user = User_Profile.objects.filter(user=self.request.user)[0]
                redirect_uri = "https://"+ self.request.META["HTTP_HOST"]+"/zoom/"
                print("redirect_uri",redirect_uri)
                zoom_url = ('https://zoom.us/oauth/token?'
                            'grant_type=authorization_code&'
                            'code={}&'
                            'redirect_uri={}')
                zoom_api_response = requests.post(zoom_url.format(zoom_OAUTH[0],redirect_uri),headers = {"Authorization":"Basic aTFsbkt3QjhUTEtpcGdfTW41SExuUTpuVjJGZHY5akh5TUN5cDRqVWdhaGZuRk91V1NVSnNPRg=="}).json()
                #  upon reciving the response save zoom credtials to the user info
                print("zoom_api_response",zoom_api_response)
                access_token = zoom_api_response["access_token"]
                refresh_token = zoom_api_response["refresh_token"]
                user.zoom_access_token = access_token
                user.zoom_refresh_token = refresh_token
                user.zoom_account_linked = True
                user.zoom_access_token_exp = timezone.now() + timedelta(seconds=int(zoom_api_response["expires_in"]))
                print("future", user.zoom_access_token_exp.strftime("%B %d, %Y, %H:%M:%S"))
                print("present",timezone.now().strftime("%B %d, %Y, %H:%M:%S"))
                user.save()
                messages.info(self.request, "Zoom Account Successfully linked")

                url = reverse('core:user_account', kwargs={'username':user.user.username})
                return HttpResponseRedirect(url)
        # if stripe code is not available then go to regular page
        return super(TestZoom, self).get(self.request, *args, **kwargs)

    def post(self, *args, **kwargs):
        print("zoom post",self.request.POST)
        meetConfig =self.request.POST.getlist('zoom') if 'zoom' in self.request.POST else None
        if meetConfig != None:
            dir=json.loads(meetConfig[0])

            data= {"signature":"sig"}
            return JsonResponse(data)

    def get_context_data(self, *args, **kwargs):
        context = super(TestZoom, self).get_context_data(*args, **kwargs)

        if self.request.user.is_authenticated:
            user = User_Profile.objects.filter(user=self.request.user)[0]
            context['user_authenticated'] = "true"
            context["user_username"] = user.user.username
            context['user'] = user
            user_notifications = Notification.objects.filter(userprofile=user).order_by('-date_created')[:10]
            context['user_notifications'] = user_notifications
            # when page loads we will load the password and meeting number we got from the zoom api
            # if user is accessing this page from group page they will have a session variable stating the currrnt group they are in
            # use the variable to access the meetingnum/password
            if  'current_group_slug' in self.request.session:
                current_group = get_object_or_404(GenGroup, slug=self.request.session["current_group_slug"])
                context['zoom_add_existing_password'] = current_group.zoom_password
                context['zoom_add_existing_meeting_number'] = current_group.zoom_meeting_number
                if current_group.creator == user:
                    context['zoom_role'] = 1
                else:
                    context['zoom_role'] = 0
            else:
                context['zoom_add_existing_password']= self.request.session["zoom_add_existing_password"] if 'zoom_add_existing_password' in self.request.session else "none"
                context['zoom_add_existing_meeting_number']= self.request.session["zoom_add_existing_meeting_number"] if 'zoom_add_existing_meeting_number' in self.request.session else "none"
                context['zoom_role'] = 0
        else:
            context['user_authenticated'] = "false"
        # we need to hide these api keys in a golobal variable
        # context['tools'] =static('js/tools.js')
        context['apiSecret'] = 'kHrPcargyNAliZfiYgYZlqBXtdK9WxZCwfYJ' #JTW
        context['zoom_api_key'] = 'z9z40dCdTVaA73xCvuTjzQ' #JTW
        return context

class DisplayZoom(generic.TemplateView):
        template_name="display_zoom.html"
        def post(self, *args, **kwargs):
            # recive create meeting request
            create_zoom_meeting_username =self.request.POST.getlist('create_zoom_meeting_username') if 'create_zoom_meeting_username' in self.request.POST else None
            if create_zoom_meeting_username != None:
                # get user creating meeeting
                user = User_Profile.objects.filter(user=self.request.user)[0]
                # check if the access token has expired refresh tokent
                # note was not able to use timezone.now because I was getting an error saying it was referenced before assignment
                # convert awaretimezone back to naicve local time
                utc=pytz.UTC
                zoom_access_token_exp = user.zoom_access_token_exp
                est=pytz.timezone('America/Phoenix') #respective to the individuals time zone we can get it from the zoom information
                zoom_access_token_exp=zoom_access_token_exp.astimezone(est)
                now = utc.localize(datetime.now())
                # convert both times to date time object
                zoom_access_token_exp = datetime(zoom_access_token_exp.year, zoom_access_token_exp.month, zoom_access_token_exp.day, zoom_access_token_exp.hour,zoom_access_token_exp.minute)
                now = datetime(now.year, now.month,now.day, now.hour, now.minute)

                # print("zoom ac",zoom_access_token_exp)
                # print("now",now)
                # checking experiation date on acesss token
                if now > zoom_access_token_exp:

core/templates/autocomplete0.html
<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<style>
* {
  box-sizing: border-box;
}

body {
  font: 16px Arial;
}

/*the container must be positioned relative:*/
.autocomplete {
  position: relative;
  display: inline-block;
}

input {
  border: 1px solid transparent;
  background-color: #f1f1f1;
  padding: 10px;
  font-size: 16px;
}

input[type=text] {
  background-color: #f1f1f1;
  width: 100%;
}

input[type=submit] {
  background-color: DodgerBlue;
  color: #fff;
  cursor: pointer;
}

.autocomplete-items {
  position: absolute;
  border: 1px solid #d4d4d4;
  border-bottom: none;
  border-top: none;
  z-index: 99;
  /*position the autocomplete items to be the same width as the container:*/
  top: 100%;
  left: 0;
  right: 0;
}

.autocomplete-items div {
  padding: 10px;
  cursor: pointer;
  background-color: #fff;
  border-bottom: 1px solid #d4d4d4;
}

/*when hovering an item:*/
.autocomplete-items div:hover {
  background-color: #e9e9e9;
}

/*when navigating through the items using the arrow keys:*/
.autocomplete-active {
  background-color: DodgerBlue !important;
  color: #ffffff;
}
</style>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>

</head>
<body>

<h2>Autocomplete</h2>

<p>Start typing:</p>

<!--Make sure the form has the autocomplete function switched off:-->
<form autocomplete="off" action="/action_page.php">
  <div class="autocomplete" style="width:300px;">
    <input id="myInput" type="text" name="myCountry" placeholder="Stock">
  </div>
  <input type="submit">
</form>

<script>
function autocomplete(inp, arr) {
  /*the autocomplete function takes two arguments,
  the text field element and an array of possible autocompleted values:*/
  var currentFocus;
  /*execute a function when someone writes in the text field:*/
  inp.addEventListener("input", function(e) {
      var a, b, i, val = this.value;
      /*close any already open lists of autocompleted values*/
      closeAllLists();
      if (!val) { return false;}
      currentFocus = -1;
      /*create a DIV element that will contain the items (values):*/
      a = document.createElement("DIV");
      a.setAttribute("id", this.id + "autocomplete-list");
      a.setAttribute("class", "autocomplete-items");
      /*append the DIV element as a child of the autocomplete container:*/
      this.parentNode.appendChild(a);
      /*for each item in the array...*/
      for (i = 0; i < arr.length; i++) {
        /*check if the item starts with the same letters as the text field value:*/
        if (arr[i].substr(0, val.length).toUpperCase() == val.toUpperCase()) {
          /*create a DIV element for each matching element:*/
          b = document.createElement("DIV");
          /*make the matching letters bold:*/
          b.innerHTML = "<strong>" + arr[i].substr(0, val.length) + "</strong>";
          b.innerHTML += arr[i].substr(val.length);
          /*insert a input field that will hold the current array item's value:*/
          b.innerHTML += "<input type='hidden' value='" + arr[i] + "'>";
          /*execute a function when someone clicks on the item value (DIV element):*/
          b.addEventListener("click", function(e) {
              /*insert the value for the autocomplete text field:*/
              inp.value = this.getElementsByTagName("input")[0].value;
              /*close the list of autocompleted values,
              (or any other open lists of autocompleted values:*/
              closeAllLists();
          });
          a.appendChild(b);
        }
      }
  });
  /*execute a function presses a key on the keyboard:*/
  inp.addEventListener("keydown", function(e) {
      var x = document.getElementById(this.id + "autocomplete-list");
      if (x) x = x.getElementsByTagName("div");
      if (e.keyCode == 40) {
        /*If the arrow DOWN key is pressed,
        increase the currentFocus variable:*/
        currentFocus++;
        /*and and make the current item more visible:*/
        addActive(x);
      } else if (e.keyCode == 38) { //up
        /*If the arrow UP key is pressed,
        decrease the currentFocus variable:*/
        currentFocus--;
        /*and and make the current item more visible:*/
        addActive(x);
      } else if (e.keyCode == 13) {
        /*If the ENTER key is pressed, prevent the form from being submitted,*/
        e.preventDefault();
        if (currentFocus > -1) {
          /*and simulate a click on the "active" item:*/
          if (x) x[currentFocus].click();
        }
      }
  });
  function addActive(x) {
    /*a function to classify an item as "active":*/
    if (!x) return false;
    /*start by removing the "active" class on all items:*/
    removeActive(x);
    if (currentFocus >= x.length) currentFocus = 0;
    if (currentFocus < 0) currentFocus = (x.length - 1);
    /*add class "autocomplete-active":*/
    x[currentFocus].classList.add("autocomplete-active");
  }
  function removeActive(x) {
    /*a function to remove the "active" class from all autocomplete items:*/
    for (var i = 0; i < x.length; i++) {
      x[i].classList.remove("autocomplete-active");
    }
  }
  function closeAllLists(elmnt) {
    /*close all autocomplete lists in the document,
    except the one passed as an argument:*/
    var x = document.getElementsByClassName("autocomplete-items");
    for (var i = 0; i < x.length; i++) {
      if (elmnt != x[i] && elmnt != inp) {
        x[i].parentNode.removeChild(x[i]);
      }
    }
  }
  /*execute a function when someone clicks in the document:*/
  document.addEventListener("click", function (e) {
      closeAllLists(e.target);
  });
}

/*An array containing all the country names in the world:*/
var countries = [
{% for stock in stocks%}
"{{stock.ticker}}",
{%endfor%}
];

/*initiate the autocomplete function on the "myInput" element, and pass along the countries array as possible autocomplete values:*/
autocomplete(document.getElementById("myInput"), countries);
</script>

</body>
</html>

core/templates/create_stock_user.html
{%extends "base.html" %}

{% block content  %}
{%load crispy_forms_tags%}

<!-- Default form login -->
<section>
  <div class="container">
    <form class="text-center border border-light p-5" action="" method="post" enctype="multipart/form-data">

        <p class="h4 mb-4">Stock</p>
        {%csrf_token %}
        {{form|crispy}}



        <!-- Sign in button -->
        <button class="btn btn-info btn-block my-4" type="submit">add Stock</button>




    </form>
  </div>
</section>

{% endblock %}

core/templates/display_zoom.html
{%extends "base.html" %}
{%load staticfiles%}
{% block content  %}

<div id="iframe_container" class="container d-flex justify-content-center pt-5 mt-5">
  <iframe id="display_zoom_iframe" class="pt-5 mt-5" src="{%url 'core:zoom'%}" width="100%" height="500px" allowfullscreen="" frameborder="0"></iframe>
  <!-- <button onclick="add_iframe()" type="button" name="button">add iframe</button>
<button onclick="remove_iframe()" type="button" name="button">remove iframe </button> -->

<!-- <iframe src="https://us04web.zoom.us/j/124423509?pwd=bE14U3Z2WGxDZms1OElSTklCaWFqUT09" width="1000" height="500" sandbox="allow-same-origin allow-forms allow-scripts" allow="microphone; camera"></iframe> -->

</div>
<div class="container d-flex justify-content-center ">
  {% if group_admin_zoom_account_linked == "true" %}
  <a onclick="zoom_create_meeting()" target="_blank" rel="noopener noreferrer"><img class="px-2 pb-1" width="32" height="32" src="{% static 'play-button.svg' %}" />Start Zoom Meeting</a>
  <div style="display:none">Icons made by <a href="https://www.flaticon.com/authors/those-icons" title="Those Icons">Those Icons</a> from <a href="https://www.flaticon.com/" title="Flaticon">www.flaticon.com</a></div>
  {%else%}
  <a href="https://zoom.us/oauth/authorize?client_id=i1lnKwB8TLKipg_Mn5HLnQ&response_type=code&redirect_uri=http%3A%2F%2F192.168.0.46%3A24%2Fzoom%2F" target="_blank" rel="noopener noreferrer"><img src="https://marketplacecontent.zoom.us/zoom_marketplace/img/add_to_zoom.png" height="32" alt="Add to ZOOM" /></a>
  {%endif%}
</div>

<div class="text-center">
  <a href="" class="btn btn-default btn-rounded mb-4" data-toggle="modal" data-target="#modalLoginForm">add created meeting here</a>
</div>

<!-- add existing meeting modal  -->
<div class="modal fade" id="modalLoginForm" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
  aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header text-center">
        <h4 class="modal-title w-100 font-weight-bold">Meeting link</h4>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body mx-3">
        <button id="zoom_add_existing_meeting_close_modal"  type="button" class="close" data-dismiss="modal" aria-label="Close">
          </button>
        <form class="text-center p-2"  method="post">
        <div >
          <input  type="url" id="zoom_meeting_url" class="form-control mb-4" placeholder="meeting url">
        </div>
          </form>
          <div class=" d-flex justify-content-center">
            <button onclick="zoom_add_existing_meeting()" class="btn btn-default">Login</button>
          </div>
      </div>

    </div>
  </div>
</div>

<!-- create meeting modal start url -->
<div class="modal fade" id="zoom_start_meeting_modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
  aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header text-center">
        <h4 class="modal-title w-100 font-weight-bold">Start Zoom meeting </h4>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body mx-3">
        <button id="zoom_create_meeting_close_modal"  type="button" class="close" data-dismiss="modal" aria-label="Close"></button>

        <a id="zoom_create_meeting_modal_button"  class="btn btn-default btn-rounded mb-4" href="">Open Zoom</a>

        <embed id="embedded_zoom"  style="width:400px; height: 500px;">
    </div>
  </div>
</div>
<a style="display:none" id="start_meeting_url_button" href="" class="btn btn-default btn-rounded mb-4" data-toggle="modal" data-target="#zoom_start_meeting_modal">Open Zoom</a>




<script>
  //when user clicks create meeting send a request to create zoom meeting
  function zoom_create_meeting() {
    $.ajaxSetup({
    data: {csrfmiddlewaretoken: '{{ csrf_token }}' },
    });

    $.ajax({
    type: "POST",
    url:"{% url 'core:zoomdisplay' %}",
    data: {
    "create_zoom_meeting_username":"{{user_username}}"
    },
     dataType: "json", //have to add in the data type
    success: function (data) {

        window.open(data["start_url"]);
    }
    });

  }

  function zoom_add_existing_meeting() {
    // Overview
    // get zoom url input to send to zoom page to join user to meeting //note the why is important
    //get the index of j because it indicates where meeting and password will be in url /j/950..
    // break up the url on th slash
    // get the meeting numbers
    //check to see if there is a password so we know if we should call the api or not
    zoom_meeting_url=document.getElementById("zoom_meeting_url").value
    j_index = zoom_meeting_url.indexOf("j")
    meeting_number = splitValue(zoom_meeting_url, j_index)
    meeting_number=meeting_number.split('/')
    // https://regex101.com/r/cL3rI3/2/codegen?language=javascript
    // get meeting number from url  stop on question mark
            const regex = /(\d+)(?=.*\?)/gm;
            const str = meeting_number;
            let m;
            var meeting_num
            while ((m = regex.exec(str)) !== null) {
                // This is necessary to avoid infinite loops with zero-width matches
                if (m.index === regex.lastIndex) {
                    regex.lastIndex++;
                }
                // The result can be accessed through the `m`-variable.
                m.forEach((match, groupIndex) => {
                    console.log(`Found match, group ${groupIndex}: ${match}`);
                    meeting_num=match
                });
            }

    //meeting number
    meeting_number =meeting_num
    if(typeof meeting_number === 'undefined') {
      meeting_number = splitValue(zoom_meeting_url, j_index)
      meeting_number=meeting_number.split('/')
      meeting_number = meeting_number[1]
    }
    console.log("meeting_number",meeting_number)
    // findout if there is a password in the url
    pwd_index = zoom_meeting_url.indexOf("pwd")
    // pwd index shows up as -1 if there is no pwd
    if (pwd_index != -1) {
        password = "true"
    }else {
        password = "false"
    }
    $.ajaxSetup({
    data: {csrfmiddlewaretoken: '{{ csrf_token }}' },
    });
    $.ajax({
    type: "POST",
    url:"{% url 'core:zoomdisplay' %}",
    data: {
    "zoom_add_existing_meeting_number":meeting_number,
    "zoom_add_existing_meeting_password":password
    },
     dataType: "json", //have to add in the data type
    success: function (data) {
      // close modal
   $("#zoom_add_existing_meeting_close_modal").click()
      // reload zoom
      document.getElementById('display_zoom_iframe').contentWindow.location.reload();
    }
    });

  }
  function remove_iframe() {
    document.getElementById('display_zoom_iframe').parentNode.removeChild( document.getElementById('display_zoom_iframe'));

  }
  function add_iframe() {
    document.getElementById("iframe_container").insertAdjacentHTML('beforeEnd', '  <iframe id="display_zoom_iframe" class="pt-5 mt-5" src="{%url 'core:zoom'%}" width="100%" height="500px" allowfullscreen="" frameborder="0"></iframe>');
    document.getElementById('display_zoom_iframe').contentWindow.location.reload();

  }

  //function to split url and get the second half
  function splitValue(value, index) {
    return value.substring(index);
}
</script>
{%endblock%}

core/templates/test.html
<script type="text/javascript"
  src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<script type="text/javascript">
  $(document).ready(function() {<!--   w w w .j a  v  a 2s.  c  o  m-->
    $("*", document.body).click(function(e) {
      e.stopPropagation();
      var domEl = $(this).get(0);
      console.log(domEl)
      // $("span:first").text("Clicked on - " + domEl.tagName);
    });
  });

}


// $( "#profile-tab-classic-shadow" ).mouseover(function() {
//   $( "#log" ).append( "<div>Handler for .mouseover() called.</div>" );
// });
</script>






var domEL;
var x =1;
$(document).ready(function() {


  $("*", document.body).click(function(e) {
    e.stopPropagation();

console.log(x)
      if (x==1) {


    console.log("3jello")

    var domEl = $(this).get(0);
  //$(this).submit(e);
    console.log(domEl.id)
    var id = domEl.id;
    post = document.getElementById("pills-home-tab")
    groups = document.getElementById("pills-profile-tab")
    rooms = document.getElementById("pills-contact-tab")
    feed = document.getElementById("pills-home-tab")
    if (id ==post) {
      console.log("hello")
      document.getElementById("pills-home-tab").click()
}
    if (id ==groups) {
      document.getElementById("pills-profile-tab").click()
    };
    if (id ==rooms) {
      document.getElementById("pills-contact-tab").click()
    };
    if (id ==feed) {
      document.getElementById("pills-home-tab").click()
    };
    console.log(id);
    var vab = $("#look").val(id);
    console.log(vab);

    myButton = document.getElementById("name");
    console.log( myButton.value);
    myButton.value = id;

    console.log( myButton.value);

}
x=x+1
if(x == 15){
x=0

}
    // $("span:first").text("Clicked on - " + domEl.tagName);
  });

});

core/templates/user_profile_form.html
{%extends "base.html" %}

{% block content  %}
{%load crispy_forms_tags%}


<!-- Default form login -->
<section>
  <div class="container">
    <form class="text-center border border-light p-5" action="" method="post" enctype="multipart/form-data">

        <p class="h4 mb-4">UserProfile</p>
        {%csrf_token %}
        {{form|crispy}}



        <!-- Sign in button -->
        <button class="btn btn-info btn-block my-4" type="submit">Next</button>




    </form>
  </div>
</section>

{% endblock %}