core/urls.py
from django.urls import path, re_path
from . import views


app_name = 'core'

urlpatterns = [
# page for practice circle canvas and netflix scroller
path('menu/',views.HtmlPractice.as_view(), name='practice'),
path('userprofile/create/',views.User_Profile_Create.as_view(), name = 'user_create'),
path('userprofile/update/<slug>/',views.User_Profile_Update.as_view(), name = 'user_update'),

path('group/<slug>/',views.Detail_Group.as_view(), name ='group'),

path('',views.User_Dashboard.as_view(),name ='user_dashboard'),

# zoom
path('zoom/',views.TestZoom.as_view(), name ='zoom'),
path('zoom-display/',views.DisplayZoom.as_view(), name ='zoomdisplay'),

#urls related to posting /////////////////
path('profile/post/<int:pk>/',views.Detail_Post.as_view(), name ='post-detail'),

#group_send
#oage to create group
path('group-create/',views.Create_DividendWealthGroup.as_view(), name ='create-group'),

#group landing page
path('group/<slug>/landing-page/',views.Group_Landing_Page.as_view(), name ='group-landing'),

path('feed/',views.Feed.as_view(), name ='feed'),
#<int:pk>
path('ajax/',views.TestAjax.as_view(), name='ajax'),
# page for user to choose membership
path('memberships/',views.Membership_Choice.as_view(), name ='membership_choice'),
#page for user account
path('account/<username>/',views.DividendWealthAccount.as_view(), name ='user_account'),

#useful test zone below
]

templates/base.html
{% load staticfiles%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    {% load sass_tags %}

    <link href="{% sass_src 'scss/loader.scss' %}" rel="stylesheet" type="text/css" />
      <!-- Font Awesome -->
      <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css">
      <!-- Bootstrap core CSS -->
      <link href="{% static "dist/css/bootstrap.min.css" %}" rel="stylesheet">
      <!-- Material Design Bootstrap -->
      <link href="{% static "dist/css/mdb-pro.min.css" %}" rel="stylesheet">
      <!-- semantic Ui -->
      <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/semantic-ui@2.4.2/dist/semantic.min.css">
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/components/dropdown.css">

      <link rel="stylesheet" href="{% static "css/steppers.min.css" %}">
      <script type="text/javascript" src="{% static "js/loader.js" %}"></script>
      <title>Dividend Wealth</title>
      <link rel="shortcut icon" type="image/jpg"href="{% static "img/logo.jpg" %}">
      {% block head_title %}{% endblock %}
      {% block extra_head %}
      {% endblock %}

  <!-- <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous"> -->
  <link href="{% static "css/github.css" %}" rel="stylesheet">

  <!-- for chartit -->
  {% load chartit%}
  <!-- jquery needs to be version one -->
  <!-- <script
    src="https://code.jquery.com/jquery-1.12.4.min.js"
    integrity="sha256-ZosEbRLbNQzLpnKIkEdrPv7lOy9C27hHQ+Xp8a4MxAQ="
    crossorigin="anonymous"></script> -->

    <style media="screen" type="text/css">
  .layer1_class {  z-index: 1; top: 100px; left: 0px; visibility: visible; }
  .layer2_class { visibility: hidden }
</style>
<script>
//https://codepen.io/colinhorn/pen/zdNMVy
  function downLoad(){
    if (document.all){
        document.all["layer1"].style.visibility="hidden";
        document.all["layer2"].style.visibility="visible";
    } else if (document.getElementById){
        node = document.getElementById("layer1").style.visibility='hidden';
        node = document.getElementById("layer2").style.visibility='visible';
    }
  }
</script>

      <style type="text/css">
      .button-boder-radius{
        border-radius: .28571429rem;
      }
      #button-line-height{
        line-height: 2;
      }
      .nav-scroller {
        height:400px;
        overflow-y: scroll;
          -webkit-overflow-scrolling: touch;
      }
      .nav-scroller::-webkit-scrollbar {
        display: none;
      }
      #bootstrap-overrides a:focus,#bootstrap-overrides a:hover, #bootstrap-overrides a   { /* 100+1=101 priority score, yay! */
        line-height: 2;
        color: inherit !important;
        text-decoration: none  !important;
      }
      .black-text, .md-toast-close-button:focus, .md-toast-close-button:hover {
    color: #e7e7e7!important;
}
      </style>



    <script async type="text/javascript" src="{% static "dist/js/jquery-3.4.1.min.js" %}"></script>
    <!-- Bootstrap tooltips -->
    <script defer type="text/javascript"  src="{% static "dist/js/popper.min.js" %}"></script>
    <!-- Bootstrap core JavaScript -->
    <script defer type="text/javascript"  src="{% static "dist/js/bootstrap.min.js" %}"></script>
    <!-- MDB core JavaScript -->
    <script defer type="text/javascript" src="{% static "dist/js/mdb.min.js" %}">
    </script>
    <script defer type="text/javascript"  src="{% static "js/steppers.min.js" %}"></script>
    <script  type="text/javascript" src="https://cdn.jsdelivr.net/npm/particles.js@2.0.0/particles.min.js"></script>




    <!-- semantic ui -->
    <script defer  type="text/javascript" src="https://cdn.jsdelivr.net/npm/semantic-ui@2.4.2/dist/semantic.min.js"></script>
    <script defer type="text/javascript"src="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/components/dropdown.js"></script>


</head>
<body onload="downLoad()" class="fixed-sn black-skin layer1_class">

  <div id="layer1" class="layer1_class">
    <div class="e-loadholder">
    	<div class="m-loader">
    		<span class="e-text">Loading</span>
    	</div>
    </div>
    <div id="particleCanvas-Blue"></div>
    <div id="particleCanvas-White"></div>
  </div>
<div id="layer2" class="layer2_class">


  {% block zoom_body %}
  <!--Double navigation-->
  <!-- SideNav slide-out button -->
<div class="mb-5">
  <!-- Sidebar navigation -->
  <div id="slide-out" class="side-nav sn-bg-4 ">
    <ul class="custom-scrollbar">
      <!-- Logo -->
      <li>
        <div class="logo-wrapper waves-light">
          <a href="#"><img src="{% static "img/logo.jpg" %}" alt="My image" class="img-fluid flex-center"></a>
        </div>
      </li>
      <!--/. Logo -->
      <!--Social-->
      <li>
        <ul class="social">
          <li><a href="#" class="icons-sm fb-ic"><i class="fab fa-facebook-f"> </i></a></li>
          <li><a href="#" class="icons-sm pin-ic"><i class="fab fa-pinterest"> </i></a></li>
          <li><a href="#" class="icons-sm gplus-ic"><i class="fab fa-google-plus-g"> </i></a></li>
          <li><a href="#" class="icons-sm tw-ic"><i class="fab fa-twitter"> </i></a></li>
        </ul>
      </li>
      <!--/Social-->
      <!--Search Form-->

      <!--/.Search Form-->
      <!-- Side navigation links -->
<li>
        <ul class="collapsible collapsible-accordion button-line-height nav-scroller">
            <li >
              <div id="bootstrap-overrides" >
                <a href="{%url 'core:membership_choice'%}"   class="cancela btn btn-primary btn-sm button-boder-radius button-line-height waves-effect waves-light hoverable">Wealth Partner</a>
              </div>
            </li>
              {% if request.user.is_authenticated%}
              <li>
                <a href="{% url 'core:user_dashboard'%}" class="waves-effect arrow-r">
                    <i class="fas fa-chart-pie mr-3"></i>Dashboard</a>
              </li>
          {%endif%}
         <li><a href="{% url 'core:feed' %}" class="waves-effect arrow-r">
           <i class="fas fa-map mr-3"></i>Discover</a></li>
        </ul>
      </li>
      <!--/. Side navigation links -->
    </ul>
    <div class="sidenav-bg mask-strong"></div>
  </div>
  <!--/. Sidebar navigation -->
  <!-- Navbar -->
  <nav class="navbar fixed-top navbar-toggleable-md navbar-expand-sm scrolling-navbar double-nav">
    <!-- SideNav slide-out button -->
      <button href="#" style="display:inline"  data-activates="slide-out" class="visible-lg button-collapse black-text navbar-toggler"><i class="fas fa-bars"></i></button>
    <!-- Breadcrumb-->
    <div class="mr-auto">
      <p>Dividend Wealth</p>
    </div>
    <!-- <a href="#" data-activates="slide-out" class="btn  black-text button-collapse mt-5"><i
        class="fas fa-bars"></i></a> -->
    <ul class="nav navbar-nav nav-flex-icons ml-auto">
      {% if request.user.is_authenticated%}
      <li class="nav-item">
          <span class="clearfix d-none d-sm-inline-block">
            <a href="{%url 'core:membership_choice'%}" class="btn btn-primary btn-sm button-boder-radius button-overflow waves-effect waves-light hoverable">Wealth Partner</a>
          </span>
      </li>
      <li class="nav-item" data-toggle="modal" data-target="#Dividend_Wealth_Notification">
        <a class="nav-link waves-effect">
          {% block notification_bell%}
          {%endblock notification_bell%}
          <i class="bell outline icon"></i>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link pl-0" href="{%url 'core:user_account' username=request.user.username %}"><i class="fas fa-user"></i></a>
      </li>
      <!-- allaut tags to login and out -->
      <li class="nav-item m-0 p-0" >
        <a class="nav-link waves-effect m-0 p-0" href="{%url 'account_logout'%}">
          <span class="nav-link"> Logout </span>
        </a>
      </li>
      {%else%}
      <li class="nav-item">
          <span class="clearfix d-none d-sm-inline-block">
            <a href="{%url 'core:membership_choice'%}" class="btn btn-primary btn-sm button-boder-radius button-overflow waves-effect waves-light hoverable">Wealth Partner</a>
          </span>
      </li>
      <li class="nav-item m-0 p-0" >
        <a class="nav-link waves-effect m-0 p-0" href="{%url 'account_login'%}">
          <span class="nav-link"> Login </span>
        </a>
      </li>
      <li class="nav-item m-0 p-0" >
        <a class="nav-link waves-effect m-0 p-0" href="{%url 'account_signup'%}">
          <span class="nav-link"> Sign Up </span>
        </a>
      </li>
      {%endif%}
      </li>
    </ul>
  </nav>
  <!-- /.Navbar -->

<!--/.Double navigation-->

</div>


  {% if messages %}
    <div class="mt-5  pt-4">
    <!-- mbd tags template  -->
      <!-- from djago messages -->
        {% for message in messages %}
        <div class="alert alert-{{ message.tags }} alert-dismissible" role="alert">
          {{ message }}
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
        </div>
        {% endfor %}
    </div>
          {% endif %}
  <!-- Navbar -->

  {% endblock zoom_body%}


  {%block jqeury%}
  {%block other_content%}

  <!-- for chartit -->




{% if request.user.is_authenticated%}

{% endif%}


{%block parac%}
{%endblock parac%}
  {% block content  %}
  {% endblock content %}




  {% block extra_body %}
  {% endblock %}



  {%endblock other_content%}
  {%endblock jqeury%}


      <script defer  type="text/javascript">
      // SideNav Initialization
              $(document).ready(function () {
                $(".button-collapse").sideNav();
            $('.stepper').mdbStepper();
            })
      </script>
      </div>
</body>
</html>

templates/main_loader.html
{% load sass_tags %}

<link href="{% sass_src 'scss/loader.scss' %}" rel="stylesheet" type="text/css" />
{%load static%}
<script  type="text/javascript" src="{% static "js/loader.js" %}"></script>
<div style="background-color:white!important" class="">


  <div class="e-loadholder">
    <div class="m-loader">
      <span class="e-text">Welthie</span>
    </div>
  </div>
  <div id="particleCanvas-Blue"></div>
  <div id="particleCanvas-White"></div>
</div>